db.Project.insertMany([
  {
    project_id: 1,
    name: "Project A",
    goal: "Caffee Shop Website",
    number_of_employees: 0,
    project_priority: "High",
    project_status: "In Progress",
    start_date: ISODate("2023-01-01"),
    end_date: null,
    project_manager_id: 1,
  },
  {
    project_id: 2,
    name: "Project F",
    goal: "Integration of AI into Existing Systems",
    number_of_employees: 0,
    project_priority: "High",
    project_status: "In Progress",
    start_date: ISODate("2023-06-15"),
    end_date: null,
    project_manager_id: 5,
  },
  {
    project_id: 3,
    name: "Project C",
    goal: "Mobile Application Development",
    number_of_employees: 0,
    project_priority: "High",
    project_status: "In Progress",
    start_date: ISODate("2023-02-28"),
    end_date: null,
    project_manager_id: 3,
  },
  {
    project_id: 4,
    name: "Project B",
    goal: "E-commerce Platform Development",
    number_of_employees: 0,
    project_priority: "Medium",
    project_status: "Pending",
    start_date: ISODate("2023-04-15"),
    end_date: null,
    project_manager_id: 2,
  },
  {
    project_id: 5,
    name: "Project D",
    goal: "Data Analysis Platform Development",
    number_of_employees: 0,
    project_priority: "Medium",
    project_status: "Pending",
    start_date: ISODate("2023-03-10"),
    end_date: null,
    project_manager_id: 4,
  },
  {
    project_id: 6,
    name: "Project E",
    goal: "Internet of Things (IoT) Solution Development",
    number_of_employees: 0,
    project_priority: "High",
    project_status: "In Progress",
    start_date: ISODate("2023-05-01"),
    end_date: null,
    project_manager_id: 6,
  },
]);
